# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Model
backbone: resnet50
num_heads: 10 # Use multiple heads

# Dataset
train_db_name: imagenet
val_db_name: imagenet
num_classes: 1000
num_neighbors: 50 

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 224
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

num_workers: 12
